spring:
  application:
    name: banking-service

server:
  port: 8082

eureka:
  client:
    register-with-eureka: { fetch-registry: true }
    service-url:
      defaultZone: http://localhost:8761/eureka